### ISSUE TITLE
手機版網頁footer會擋到按鈕

### ISSUE THREAD

**Issue by CA-Lee** [CA-Lee/2019-nCoV_annos_TW#3]
如圖，頁面無法往下滑，造成footer會擋住github repo及hackmd的連結按鈕

System:
Sony g3426
Android 8.0.0
Google chrome 80.0.3987.87

![Screenshot_20200210-113653](https://user-images.githubusercontent.com/31626425/74119315-df172f80-4bf9-11ea-92cf-700ae0dc4598.png)

**Comment by fred39392001** [comment]
好的，我晚一點找時間調整！

**Comment by CA-Lee** [comment]
btw, 因為按下「圖片下載」後就會立刻開始下載，建議改成「下載圖片」或加註

**Comment by fred39392001** [comment]
OK，等一下一併調整。

**Comment by fred39392001** [comment]
已修正。

**Comment by CA-Lee** [comment]
Merged.
