### ISSUE TITLE
口罩實名制227有新制

### ISSUE THREAD

**Issue by haruhi3745** [CA-Lee/2019-nCoV_annos_TW#6]
雲端硬碟只能移動自己上傳的檔案，還是只能開 issue 提醒了

**Comment by CA-Lee** [comment]
感謝通知，剛剛已經把過期文宣移至過期區，應該會在午夜12點更新到GITHUB。剛剛也有發現無法移動別人檔案的情況，解決方法是先移到buffer（拖曳到路徑列的buffer字上）再移到目標資料夾。
